### ISSUE TITLE
First time running ksv on a simple fmt breaks?

### ISSUE THREAD

**Issue by shiftre** [kaitai-io/kaitai_struct_visualizer#17]
```
4046010217 (of class java.lang.Long)
Compilation OK
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': no implicit conversion of nil into String (TypeError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/kaitai-struct-visualizer-0.5/lib/kaitai/struct/visualizer/visualizer_main.rb:31:in `block in compile_format'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/kaitai-struct-visualizer-0.5/lib/kaitai/struct/visualizer/visualizer_main.rb:10:in `compile_format'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/kaitai-struct-visualizer-0.5/lib/kaitai/struct/visualizer/visualizer.rb:18:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/kaitai-struct-visualizer-0.5/bin/ksv:19:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/kaitai-struct-visualizer-0.5/bin/ksv:19:in `<top (required)>'
        from C:/Ruby24-x64/bin/ksv:22:in `load'
        from C:/Ruby24-x64/bin/ksv:22:in `<main>'
```

```
meta:
  id: fmt
  application: fmt
  endian: le
seq:
  - id: magic
    contents: [0xdeadbeef]
  - id: static
    contents: [0x56000000, 0x00000000, 0x33000000, 0xdeadcode]
  - id: BaseChunk
    type: u4

```

Am I missing something?
