### ISSUE TITLE
Add ability to view local offsets

### ISSUE THREAD

**Issue by hilts-vaughan** [kaitai-io/kaitai_struct_visualizer#4]
It would be nice to be able to view "local offsets" in a repeat block. Take for example, the following YAML markup:

```
meta:
  id: scp
  application: TiTS Engine - Sprite Format
  endian: le
seq:
  - id: header
    type: header
  - id: frame_entries
    type: frame_entries
types:
  header:
    seq:
      - id: frame_count
        type: u1
      - id: magic_zero
        contents: [0]
  frame_entries:
    seq:
      - id: frame_entry
        repeat: eos

        # The pages are always 512 byte blocks / pages
        # for some reason... not sure why considering a lot of
        # the data is wasted...
        size: 512
```

It would be nice when examing the data to have "local offsets" toggalable, this would allow me to quickly deal with offsets without needing to do subtraction. :) For example, for each `frame_entry`

**Comment by GreyCat** [comment]
Can you explain in more detail what exactly you're looking for? There is a concept of "substream", which displays exactly what you're looking for: local offsets.

For example, if you change your `frame_entries` to:

```yaml
  - id: frame_entries
    type: frame_entries
    size-eos: true
```

then if will make frame_entries to use a substream, which will start where the element was going to start and will take up all space up to the end of main stream. In that substream, things will get indexed from offset 0 - that is what you mean by "local offsets"?
