### ISSUE TITLE
Error while parsing: attempted to read 1 bytes, got only 0

### ISSUE THREAD

**Issue by bersbersbers** [kaitai-io/kaitai_struct_visualizer#53]
The following format breaks parsing on `byte0`:

```
[-] [root]                                                                                                               00000000: 00 00 00 00 00 00 00 
  [-] data                                                                                                               00000010: 
    [?] byte0                                                                                                            00000020: 
    [-] byte1                                                                                                            00000030: 
      [.] ╔══════════════════════════════════════════════════════════════════════════════ Error while parsing ═════════════════════════════════════════════════════════════════════════════╗
          ║attempted to read 1 bytes, got only 0                                                                                                                                           ║
          ║                                                                                                                                                                                ║
          ║                                                                                                                                                                                ║
          ║                                                                                                                                                                                ║
          ║                                                                                                                                                                                ║
          ║                                                                                                                                                                                ║
          ║                                                                                                                                                                                ║
          ║                                                                              [ OK ]                                                                                            ║
          ║                                                                                                                                                                                ║
          ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

```yaml
meta:
  id: bug
seq:
  - id: data
    type: twobytes
types:
  twobytes:
    instances:
      byte0:
        type:
          switch-on: byte1.bit0
          cases:
            true: u1
            false: u1

      byte1:
        pos: 1
        type: byte1
  byte1:
    seq:
      - id: bit0
        type: b1
```

This one works, by contrast:
```yaml
meta:
  id: bug
seq:
  - id: data
    type: twobytes
types:
  twobytes:
    seq:
      - id: byte0
        type:
          switch-on: byte1.bit0
          cases:
            true: u1
            false: u1
    instances:
      byte1:
        pos: 1
        type: byte1
  byte1:
    seq:
      - id: bit0
        type: b1
```
And most interestingly, both work in https://ide.kaitai.io/
